using Backend.Domain.Entities;



// Class to convert models
namespace Backend.Common.Converters
{
    public static class ModelConverter
    {
        public static UserRegistrationDataModel ToRegistrationModel(UserModel user)
        {
            return new UserRegistrationDataModel
            {
                PersoId = user.PersoId,
                Email = user.Email
            };
        }

        public static UserModel ToUserModel(UserRegistrationDataModel registration, Guid persoId)
        {
            return new UserModel
            {
                PersoId = persoId, // Todo: PersoId is generated by the system, is this wrong logic?
                Email = registration.Email,
                CreatedTime = DateTime.UtcNow // Todo: Does this need to be set here?
            };
        }
    }
}
