name: CI-CD (Pi, multi-arch)

on:
  push:
    branches: [ main ]
    paths:
      - "Backend/**"
      - "Frontend/**"
      - "caddy/**"
      - "docker-compose.yml"
      - ".github/workflows/**"
  workflow_dispatch:

env:
  IMAGE: ghcr.io/${{ github.repository_owner }}/steenbudget-backend

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    environment: production-pi
    steps:
      - uses: actions/checkout@v4

      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build & push backend (linux/amd64, linux/arm64)
        run: |
          docker buildx build \
            --platform linux/amd64,linux/arm64 \
            -t $IMAGE:${{ github.sha }} \
            -t $IMAGE:latest \
            -f Backend/Dockerfile \
            --push Backend

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Build frontend
        working-directory: Frontend
        env:
          VITE_APP_API_URL: ${{ vars.VITE_APP_API_URL }}
          VITE_APP_RECAPTCHA_SITE_KEY: ${{ vars.VITE_APP_RECAPTCHA_SITE_KEY }}
        run: |
          npm ci
          npm run build
          tar czf dist.tar.gz dist

      - name: Upload frontend dist
        uses: actions/upload-artifact@v4
        with:
          name: frontend-dist
          path: Frontend/dist.tar.gz
          retention-days: 3

deploy:
  name: Deploy to Production
  runs-on: [self-hosted, pi, deploy] # Pi3 runner
  needs: build
  environment: production-pi
  steps:
    - name: Download frontend artifact
      uses: actions/download-artifact@v4
      with:
        name: frontend-dist
        path: .

    # Upload and unpack FE as 'anon' (uses anon_ci key)
    - name: Ship frontend to Pi4
      run: |
        scp -P 2222 -i /home/runner/.ssh/anon_ci -o StrictHostKeyChecking=accept-new \
          ./dist.tar.gz \
          anon@192.168.50.61:/opt/steenbudget/frontend/
        ssh -p 2222 -i /home/runner/.ssh/anon_ci anon@192.168.50.61 \
          'cd /opt/steenbudget/frontend && rm -rf dist && tar xzf dist.tar.gz && rm dist.tar.gz && chown -R anon:anon dist'

    # Trigger backend/caddy refresh via forced-command deploy key
    - name: Trigger backend deploy on Pi4
      run: |
        ssh -T -p 2222 -i /home/runner/.ssh/deploy_pi3 deploy@192.168.50.61 || true

    # Quick checks
    - name: Confirm services
      run: |
        ssh -p 2222 -i /home/runner/.ssh/anon_ci anon@192.168.50.61 \
          'docker compose -f /opt/steenbudget/docker-compose.yml ps'
        ssh -p 2222 -i /home/runner/.ssh/anon_ci anon@192.168.50.61 \
          'curl -sS -o /dev/null -w "%{http_code}\n" https://ebudget.se/health'
