name: Deploy to Raspberry Pi

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:                                        
        WEBSOCKET_SECRET: ${{ secrets.WEBSOCKET_SECRET }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to Raspberry Pi
        run: |
          # Export the frontend and backend secrets
          export VITE_APP_RECAPTCHA_SITE_KEY=${{ secrets.VITE_APP_RECAPTCHA_SITE_KEY }}
          export VITE_APP_API_URL=${{ vars.VITE_APP_API_URL }}
          export WEBSOCKET_SECRET=$WEBSOCKET_SECRET
          
          # Pass the environment variable into the ssh session
          ssh -o StrictHostKeyChecking=no -p 2222 pi@155.4.68.41 << EOF
            export WEBSOCKET_SECRET=$WEBSOCKET_SECRET
            export PATH=$PATH:/usr/share/dotnet:/usr/bin
            
            set -e
            cd /home/pi/SteenBudgetSolution

            # Discard any local changes
            echo "Resetting local changes..."
            git reset --hard
            git clean -fd
            
            echo "Current Git Status:"
            git status
            git pull origin master
            echo "After Git Pull:"
            git log -1
            
            # Ensure necessary directories exist
            sudo mkdir -p /var/www/backend
            sudo mkdir -p /var/www/html
            
            # Fix permissions for backend directory
            sudo chmod -R 777 /var/www/backend

            # Publish and deploy backend
            cd Backend
            dotnet publish /home/pi/SteenBudgetSolution/Backend/Backend.csproj -c Release -o /var/www/backend

            # Restart the backend service
            sudo systemctl restart steenbudget.service
            
            # Capture the build date and time of the application
            echo "Build completed on:"
            date "+%Y-%m-%d %H:%M:%S"
            
            # Build and deploy frontend
            cd ../Frontend
            rm -rf node_modules dist
            npm install
            
            # Fix permissions for node_modules
            sudo chmod -R 755 node_modules
            
            VITE_APP_RECAPTCHA_SITE_KEY=$VITE_RECAPTCHA_SITE_KEY VITE_APP_API_URL=$VITE_API_URL npm run build
            
            # Deploy the contents of the dist folder to the server's web directory
            sudo rm -rf /var/www/html/*
            sudo cp -r dist/* /var/www/html/
            sudo chmod -R 755 /var/www/html

            # Restart the web server
            sudo systemctl restart nginx
            
            echo "Contents of /var/www/html:"
            ls -l /var/www/html
          EOF
